// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SneakersFootprint.Models;

namespace SneakersFootprint.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220112145600_init 2")]
    partial class init2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("SneakersFootprint.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Men's Sneakers"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Women's Sneakers"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Kid's Sneakers"
                        });
                });

            modelBuilder.Entity("SneakersFootprint.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("OrderPlaced")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OrderTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SneakersFootprint.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SneakerId")
                        .HasColumnType("int");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrderId");

                    b.HasIndex("SneakerId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("SneakersFootprint.Models.ShoppingCartItem", b =>
                {
                    b.Property<int>("ShoppingCartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("ShoppingCartId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SneakerId")
                        .HasColumnType("int");

                    b.HasKey("ShoppingCartItemId");

                    b.HasIndex("SneakerId");

                    b.ToTable("ShoppingCartItems");
                });

            modelBuilder.Entity("SneakersFootprint.Models.Sneaker", b =>
                {
                    b.Property<int>("SneakerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InStock")
                        .HasColumnType("bit");

                    b.Property<string>("LongDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Sale")
                        .HasColumnType("bit");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SneakerId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Sneakers");

                    b.HasData(
                        new
                        {
                            SneakerId = 1,
                            CategoryId = 1,
                            ImageThumbnailUrl = "/Images/sko-air-huarache-le-7ggQkX.jpg",
                            ImageUrl = "/Images/sko-air-huarache-le-7ggQkX.jpg",
                            InStock = true,
                            LongDescription = "The Nike Air Huarache LE is a favorite with a street feel. A comfortable shoe with an excellent fit. The upper combines elegant leather details with a super airy, glossy neoprene-like material that provides many styling options. Classic heel clip and stripped-down brand details give a look from the early 90's.Color shown: Shadow/Black/Midnight Navy. Style: DH8143 - 400",
                            Name = "Nike Air Huarache LE",
                            Price = 1199.95m,
                            Sale = true,
                            ShortDescription = "Size. EU 42"
                        },
                        new
                        {
                            SneakerId = 2,
                            CategoryId = 2,
                            ImageThumbnailUrl = "/Images/tavlingsskor-vag-air-zoom-alphafly-next-flyknit-HqKDw4.jpg",
                            ImageUrl = "/Images/tavlingsskor-vag-air-zoom-alphafly-next-flyknit-HqKDw4.jpg",
                            InStock = true,
                            LongDescription = "Get ready to reach your next personal best in this road shoe that's made for fast movement. It gives you the best energy reproduction of all our race shoes with a forward feel all the way across the finish line. The design is lightweight, breathable and designed using scientific data to give you a comfortable fit. The details celebrate our shared ability to take on tough challenges.Color shown: White/Black/Pink. Style: DJ5456-100",
                            Name = "Nike Air Zoom Alphafly",
                            Price = 779.95m,
                            Sale = false,
                            ShortDescription = "Size. EU 39"
                        },
                        new
                        {
                            SneakerId = 3,
                            CategoryId = 3,
                            ImageThumbnailUrl = "/Images/loparskor-flex-runner-sTBg4T.jpg",
                            ImageUrl = "/Images/loparskor-flex-runner-sTBg4T.jpg",
                            InStock = true,
                            LongDescription = "Forget the lacing – you can just pull these on. Run around the block or compete with your friends – Nike Flex Runner makes everything easy. The foam sole is super flexible so that each step and jump is as easy as 1, 2, 3.Color shown: Medium Ash/Siren Red/Black. Style: AT4662-200",
                            Name = "Nike Flex Runner",
                            Price = 499.95m,
                            Sale = false,
                            ShortDescription = "Size. EU 35.5"
                        },
                        new
                        {
                            SneakerId = 4,
                            CategoryId = 1,
                            ImageThumbnailUrl = "/Images/Ultraboost_4.0_DNA_Shoes_black.jpg",
                            ImageUrl = "/Images/Ultraboost_4.0_DNA_Shoes_black.jpg",
                            InStock = true,
                            LongDescription = "Precision-made, seamless zones combine strength and function with smooth comfort to ensure interference-free movements.Color shown: Core Black. Product code: FY9121",
                            Name = "Adidas ULTRABOOST 4.0 DNA",
                            Price = 1299.95m,
                            Sale = false,
                            ShortDescription = "Size. EU 42"
                        },
                        new
                        {
                            SneakerId = 5,
                            CategoryId = 3,
                            ImageThumbnailUrl = "/Images/sko-air-max-90-ltr-BpFdfH.jpg",
                            ImageUrl = "/Images/sko-air-max-90-ltr-BpFdfH.jpg",
                            InStock = true,
                            LongDescription = "In the past, it was revolutionary. Today? Today it is iconic. The Nike Air Max 90 LTR SE is back with a design that's more suited for kids than the original. The update has a softer cushioning, more flexibility and a more comfortable feel. This special edition is inspired by medals that celebrate us all as winners.Color shown: Off Noir/Black/Summit White/Metallic Pewte. Product code: CD6864-117",
                            Name = "Nike Air Max 90 LTR",
                            Price = 1249m,
                            Sale = false,
                            ShortDescription = "Size. EU 29.5"
                        },
                        new
                        {
                            SneakerId = 6,
                            CategoryId = 3,
                            ImageThumbnailUrl = "/Images/sko-huarache-run-zsL2zh.jpg",
                            ImageUrl = "/Images/sko-huarache-run-zsL2zh.jpg",
                            InStock = true,
                            LongDescription = "The Nike Huarache Run has an unmistakable style. The shoe is equipped with the famous Huarache heel strap that allows you to easily stick your foot in it. An inner shoe that sits comfortably around the foot and provides safety and support when running, climbing and playing.Color shown: White/Off Noir/Mint Foam. Product code: 704949-116",
                            Name = "Nike Huarache Run",
                            Price = 949m,
                            Sale = false,
                            ShortDescription = "Size. EU 31"
                        },
                        new
                        {
                            SneakerId = 7,
                            CategoryId = 3,
                            ImageThumbnailUrl = "/Images/sko-flex-advance-L44DwQ.jpg",
                            ImageUrl = "/Images/sko-flex-advance-L44DwQ.jpg",
                            InStock = true,
                            LongDescription = "The Nike Flex Advance is as simple as counting to three. Nike FlyEase technology provides an extra wide opening so small feet can slide in effortlessly (seriously, it's as easy as it gets). Cross the ribbons (to prepare the kids for real shoelaces) and then it's done. They are super flexible, comfortable and durable – perfect for the little ones to walk, run and play in.Color shown: Black/Siren Red/Medium Ash/White. Product code: CZ0186-005",
                            Name = "Nike Flex Advance",
                            Price = 649m,
                            Sale = true,
                            ShortDescription = "Size. EU 36"
                        },
                        new
                        {
                            SneakerId = 8,
                            CategoryId = 3,
                            ImageThumbnailUrl = "/Images/sko-blazer-mid-77-2jP7Bp.jpg",
                            ImageUrl = "/Images/sko-blazer-mid-77-2jP7Bp.jpg",
                            InStock = true,
                            LongDescription = "Your little basketball player can own the court in the Nike Blazer Mid '77. The vintage look and comfortable feel make this classic a legendary street shoe even off the pitch..Color shown: Vit/Pecan/Vivid Sulfur. Product code: DA4087-103",
                            Name = "Nike Blazer Mid 77",
                            Price = 749m,
                            Sale = false,
                            ShortDescription = "Size. EU 31"
                        },
                        new
                        {
                            SneakerId = 9,
                            CategoryId = 3,
                            ImageThumbnailUrl = "/Images/sko-air-max-270-xK8g2Z.jpg",
                            ImageUrl = "/Images/sko-air-max-270-xK8g2Z.jpg",
                            InStock = true,
                            LongDescription = "The Nike Air Max 270 shoe combines the long Nike Air Max 180 tongue with classic elements from the Air Max 93. The model has the largest Air unit ever from Nike on its heel and is as comfortable as it looks.Color shown: Black/Black. Product code: BQ5776-001",
                            Name = "Nike Air Max 270",
                            Price = 749m,
                            Sale = false,
                            ShortDescription = "Size. EU 39"
                        },
                        new
                        {
                            SneakerId = 10,
                            CategoryId = 1,
                            ImageThumbnailUrl = "/Images/skor-air-max-plus-Pc62Zg.jpg",
                            ImageUrl = "/Images/skor-air-max-plus-Pc62Zg.jpg",
                            InStock = true,
                            LongDescription = "These sneakers are loaded with extra stability and cushioning. The top layers have stood the test of time since the original made an impression in '98.The design of the mesh material is inspired by crushed ice, creating a cool nod to outdoor activities in winter.Color shown: Black/White/Dark Smoke Grey/Black. Product code: DO6384-001",
                            Name = "Nike Air Max Plus",
                            Price = 1899m,
                            Sale = false,
                            ShortDescription = "Size. EU 40.5"
                        },
                        new
                        {
                            SneakerId = 11,
                            CategoryId = 1,
                            ImageThumbnailUrl = "/Images/sko-air-max-pre-day-W67m0w.jpg",
                            ImageUrl = "/Images/sko-air-max-pre-day-W67m0w.jpg",
                            InStock = true,
                            LongDescription = "Inspired by Nike's classic running shoes, the Nike Air Max Pre-Day features a design that creates a modern sense of speed. The shoe is a true tribute to history and is made of at least 20% recycled material in relation to its weight and has a running-inspired retro design. A new Air window attracts the eye along with an incredibly soft cushioning.Color shown: Kumquat/Photon Dust/White/Pomegranate. Product code: DC9402-800",
                            Name = "Nike Air Max Pre-Day",
                            Price = 1449m,
                            Sale = true,
                            ShortDescription = "Size. EU 43"
                        },
                        new
                        {
                            SneakerId = 12,
                            CategoryId = 1,
                            ImageThumbnailUrl = "/Images/NMD_R1_Vit_GX1050_06_standard.jpg",
                            ImageUrl = "/Images/NMD_R1_Vit_GX1050_06_standard.jpg",
                            InStock = true,
                            LongDescription = "Pack your bag, lace up your shoes and get out. City adventures call when you have these NMD_R1 shoes on your feet. These modern sneakers are an update to an acclaimed 80s running shoe from the adidas archive, with a soft and stretchy knitted upper as well as energy-restoring Boost cushioning for all-day comfort. The strong colors and distinctive plugs in the midsole serve as a statement and max out the style level wherever you go. This product is made of Primeblue, a recycled functional material partly created with Parley Ocean Plastic. 50% of the upper is made of textile, 75% of the textile is Primeblue yarn. No newly produced polyester.Color shown: Kumquat/Photon Dust/White/Pomegranate. Product code: GZ7925",
                            Name = "Adidas NMD_R1",
                            Price = 1499m,
                            Sale = true,
                            ShortDescription = "Size. EU 40"
                        },
                        new
                        {
                            SneakerId = 13,
                            CategoryId = 1,
                            ImageThumbnailUrl = "/Images/Ultraboost_1.0_DNA_Shoes_Bla_GV7723_06.jpg",
                            ImageUrl = "/Images/Ultraboost_1.0_DNA_Shoes_Bla_GV7723_06.jpg",
                            InStock = true,
                            LongDescription = "You are responsible for the energy. These running shoes from adidas give it back. That's the magic behind the legendary Ultraboost design. This pair brings the OG adidas Primeknit pattern from 2015 to life as a tribute to the beloved shoe. Lace up and experience comfort all day long. Plus style, of course.Color shown: Blue / Navy Blue / Wonder White. Product code: GV7723",
                            Name = "Adidas ULTRABOOST 1.0 DNA",
                            Price = 1949m,
                            Sale = false,
                            ShortDescription = "Size. EU 39"
                        },
                        new
                        {
                            SneakerId = 14,
                            CategoryId = 2,
                            ImageThumbnailUrl = "/Images/loparskor-hart-underlag-air-zoom-pegasus-38-rPC6SB.jpg",
                            ImageUrl = "/Images/loparskor-hart-underlag-air-zoom-pegasus-38-rPC6SB.jpg",
                            InStock = true,
                            LongDescription = "Your workhorse with wings is back in colors and shapes inspired by your winter favorites. The Nike Air Zoom Pegasus 38 Premium continues to give you extra weight in the step, with the same responsive foam material as its predecessor. Airy mesh combines the comfortable feel and durability you want with a wider fit at the toes. Get out with a running classic with a winter-inspired twist.Color shown: Blue Tint/Regal Pink/Light Smoke Grey/Multicolored. Product code: DC8796-400",
                            Name = "Nike Air Zoom Pegasus 38",
                            Price = 1399m,
                            Sale = false,
                            ShortDescription = "Size. EU 41.5"
                        },
                        new
                        {
                            SneakerId = 15,
                            CategoryId = 2,
                            ImageThumbnailUrl = "/Images/sko-air-max-270-WM5Xd6.jpg",
                            ImageUrl = "/Images/sko-air-max-270-WM5Xd6.jpg",
                            InStock = true,
                            LongDescription = "Nike's first lifestyle Air Max gives you style, a comfortable feel and the right attitude in the Nike Air Max 270. Inspired by Air Max icons, the design showcases Nike's greatest innovation with its large window and new colors.Color shown: White/White/Black. Style: AH6789-100",
                            Name = "Nike Air Max 270",
                            Price = 1699m,
                            Sale = false,
                            ShortDescription = "Size. EU 42"
                        },
                        new
                        {
                            SneakerId = 16,
                            CategoryId = 2,
                            ImageThumbnailUrl = "/Images/sko-dunk-low-se-GpdDGH.jpg",
                            ImageUrl = "/Images/sko-dunk-low-se-GpdDGH.jpg",
                            InStock = true,
                            LongDescription = "It was created for the basketball court but became an icon of street fashion. Now the basketball icon is back with metallic animal patterns and details that show off your wild side. The classic Nike Dunk Low SE basketball look gives you vintage-inspired style and the padded, low heel cap makes this model extra comfortable.Color shown: Fossil Stone/Fossil Stone/Multicolored. Style: DD7099-200",
                            Name = "Nike Dunk Low SE",
                            Price = 1249m,
                            Sale = true,
                            ShortDescription = "Size. EU 39"
                        },
                        new
                        {
                            SneakerId = 17,
                            CategoryId = 2,
                            ImageThumbnailUrl = "/Images/golfsko-air-max-270-g-qdKfmN.jpg",
                            ImageUrl = "/Images/golfsko-air-max-270-g-qdKfmN.jpg",
                            InStock = true,
                            LongDescription = "Get a legendary look with the Nike Air Max 270 G. The silhouette is an accurate reconstruction of the classic Air model but has been updated with airy mesh material and an innovative grip for top-level gaming.Color shown: Black/Hot Punch/White. Style: CK6483-001",
                            Name = "Nike Air Max 270 G",
                            Price = 1699m,
                            Sale = true,
                            ShortDescription = "Size. EU 40"
                        },
                        new
                        {
                            SneakerId = 18,
                            CategoryId = 2,
                            ImageThumbnailUrl = "/Images/basketsko-lebron-19-jFVxZC.jpg",
                            ImageUrl = "/Images/basketsko-lebron-19-jFVxZC.jpg",
                            InStock = true,
                            LongDescription = "LeBron likes when the stakes are high and the pressure is hard. LeBron 19 harnesses that energy with a molded fit and an updated cushioning system. The tight inner shoe is held together by a molded top layer. The shoelaces go through the top layer and prevent the foot from moving inside the shoe. Embedded cushions in the tongue and heel cap provide lower weight and support for the ankle. It gives the player a confident feeling and the confidence to give everything to decide the match.Color shown: Mantra Orange/University Gold/University Red/Light Blue Fury. Style: DC9338-800",
                            Name = "Nike LeBron 19",
                            Price = 1699m,
                            Sale = true,
                            ShortDescription = "Size. EU 41"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SneakersFootprint.Models.OrderDetail", b =>
                {
                    b.HasOne("SneakersFootprint.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SneakersFootprint.Models.Sneaker", "Sneaker")
                        .WithMany()
                        .HasForeignKey("SneakerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Sneaker");
                });

            modelBuilder.Entity("SneakersFootprint.Models.ShoppingCartItem", b =>
                {
                    b.HasOne("SneakersFootprint.Models.Sneaker", "Sneaker")
                        .WithMany()
                        .HasForeignKey("SneakerId");

                    b.Navigation("Sneaker");
                });

            modelBuilder.Entity("SneakersFootprint.Models.Sneaker", b =>
                {
                    b.HasOne("SneakersFootprint.Models.Category", "Category")
                        .WithMany("Sneakers")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SneakersFootprint.Models.Category", b =>
                {
                    b.Navigation("Sneakers");
                });

            modelBuilder.Entity("SneakersFootprint.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
